[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[profile.tokens]
src = 'src-tokens'
out = 'out'
libs = ['lib-tokens']
remappings = [
]

[profile.stable-staking]
src = 'src-stable_staking'
out = 'out'
libs = ['lib-stable-staking']
remappings = [
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
